<?php

namespace App\Console\Commands;

use App\Models\Page;
use Illuminate\Console\Command;

/**
 * Export CMS pages (no site_settings / Stripe keys).
 *
 * @see https://laravel.com/docs/13.x/artisan
 */
class ExportCmsPagesCommand extends Command
{
    protected $signature = 'site:export-cms-pages
                            {--stdout : Print PHP return payload instead of writing the seeder file}';

    protected $description = 'Export CMS pages for local parity (no integration secrets)';

    public function handle(): int
    {
        $pages = Page::query()->orderBy('id')->get()->map(function (Page $page): array {
            return [
                'key' => $page->key,
                'template' => $page->template,
                'is_published' => (bool) $page->is_published,
                'title' => $page->getTranslations('title'),
                'slug' => $page->getTranslations('slug'),
                'body' => $page->getTranslations('body'),
                'meta' => $page->meta,
            ];
        })->all();

        $payload = $this->phpReturnFile($pages);

        if ($this->option('stdout')) {
            $this->output->write($payload);

            return self::SUCCESS;
        }

        $path = database_path('seeders/data/deploy-pages.php');
        file_put_contents($path, $payload);
        $this->info('Exported:');
        $this->line('  '.$path);

        return self::SUCCESS;
    }

    /**
     * @param  list<array<string, mixed>>  $pages
     */
    private function phpReturnFile(array $pages): string
    {
        $export = var_export($pages, true);

        return <<<PHP
<?php

/**
 * CMS pages for local/production content parity.
 *
 * Generated by: php artisan site:export-cms-pages
 * Does not include site_settings or Stripe keys.
 *
 * @see https://laravel.com/docs/13.x/artisan
 */
return {$export};

PHP;
    }
}
