<?php

namespace App\Console\Commands;

use App\Models\Article;
use App\Models\ArticleCategory;
use App\Services\SiteSettingsService;
use Illuminate\Console\Command;

class ExportDeployDataCommand extends Command
{
    protected $signature = 'site:export-deploy-data';

    protected $description = 'Export CMS articles and integration settings for production deploy seeders';

    public function handle(SiteSettingsService $settings): int
    {
        $integrationPath = database_path('seeders/data/deploy-integrations.php');
        $articlesPath = database_path('seeders/data/deploy-articles.php');

        $integrationSettings = [];

        foreach (array_keys(config('site_settings.keys', [])) as $key) {
            $value = $settings->get($key);

            if ($value !== '') {
                $integrationSettings[$key] = $value;
            }
        }

        if (isset($integrationSettings['espocrm.base_url']) && app()->environment('local')) {
            $integrationSettings['espocrm.base_url'] = 'https://crm.safehouse.community';
        }

        unset($integrationSettings['espocrm.api_key'], $integrationSettings['stripe.webhook_secret']);

        $this->writePhpReturnFile($integrationPath, $integrationSettings, 'Integration defaults for production deploy');

        $categories = ArticleCategory::query()->get()->map(function (ArticleCategory $category): array {
            return [
                'slug_it' => $category->getTranslation('slug', 'it'),
                'name' => $category->getTranslations('name'),
                'slug' => $category->getTranslations('slug'),
                'description' => $category->getTranslations('description'),
            ];
        })->all();

        $articles = Article::query()->get()->map(function (Article $article): array {
            $category = $article->category;

            return [
                'category_slug_it' => $category?->getTranslation('slug', 'it'),
                'title' => $article->getTranslations('title'),
                'slug' => $article->getTranslations('slug'),
                'excerpt' => $article->getTranslations('excerpt'),
                'body' => $article->getTranslations('body'),
                'is_published' => $article->is_published,
                'published_at' => $article->published_at?->toIso8601String(),
            ];
        })->all();

        $this->writePhpReturnFile($articlesPath, [
            'categories' => $categories,
            'articles' => $articles,
        ], 'CMS articles for production deploy');

        $this->info('Exported:');
        $this->line('  '.$integrationPath);
        $this->line('  '.$articlesPath);

        return self::SUCCESS;
    }

    /**
     * @param  array<string, mixed>  $data
     */
    private function writePhpReturnFile(string $path, array $data, string $comment): void
    {
        $export = var_export($data, true);

        $contents = <<<PHP
<?php

/**
 * {$comment}
 *
 * Generated by: php artisan site:export-deploy-data
 */
return {$export};

PHP;

        file_put_contents($path, $contents);
    }
}
