<?php

namespace App\Console\Commands;

use App\Models\Article;
use App\Models\ArticleCategory;
use Illuminate\Console\Command;

class ExportDeployDataCommand extends Command
{
    protected $signature = 'site:export-deploy-data';

    protected $description = 'Export CMS articles for production deploy seeders';

    public function handle(): int
    {
        $articlesPath = database_path('seeders/data/deploy-articles.php');

        $categories = ArticleCategory::query()->get()->map(function (ArticleCategory $category): array {
            return [
                'slug_it' => $category->getTranslation('slug', 'it'),
                'name' => $category->getTranslations('name'),
                'slug' => $category->getTranslations('slug'),
                'description' => $category->getTranslations('description'),
            ];
        })->all();

        $articles = Article::query()->get()->map(function (Article $article): array {
            $category = $article->category;

            return [
                'category_slug_it' => $category?->getTranslation('slug', 'it'),
                'title' => $article->getTranslations('title'),
                'slug' => $article->getTranslations('slug'),
                'excerpt' => $article->getTranslations('excerpt'),
                'body' => $article->getTranslations('body'),
                'meta' => $article->meta,
                'is_published' => $article->is_published,
                'published_at' => $article->published_at?->toIso8601String(),
            ];
        })->all();

        $this->writePhpReturnFile($articlesPath, [
            'categories' => $categories,
            'articles' => $articles,
        ], 'CMS articles for production deploy');

        $this->info('Exported:');
        $this->line('  '.$articlesPath);

        return self::SUCCESS;
    }

    /**
     * @param  array<string, mixed>  $data
     */
    private function writePhpReturnFile(string $path, array $data, string $comment): void
    {
        $export = var_export($data, true);

        $contents = <<<PHP
<?php

/**
 * {$comment}
 *
 * Generated by: php artisan site:export-deploy-data
 */
return {$export};

PHP;

        file_put_contents($path, $contents);
    }
}
