<?php

/**
 * Integration defaults for production deploy
 *
 * Generated by: php artisan site:export-deploy-data
 */
return array (
  'stripe.key' => 'pk_test_51TfltZ1XvMWH96Ksxj2asWf6N6l9oEonWNXiK5GF9fbiaSbaYqmL3cBc6RnNj2TYUZwNtrHsfwfGM0MpN0NwlOYY00IqgDCSis',
  'stripe.secret' => 'sk_test_51TfltZ1XvMWH96KsEth3pgnpTz0J12Zb0domDLHm4jdT4ACq1kDLncswvynxIXlxMfbnfrQgVu6FXfiazMppqPQb00EceOnNn6',
  'stripe.currency' => 'EUR',
  'stripe.statement_descriptor' => 'SAFE HOUSE',
  'stripe.account_id' => 'acct_1TfltZ1XvMWH96Ks',
  'stripe.account_name' => 'Safe House',
  'espocrm.base_url' => 'https://crm.safehouse.community',
  'espocrm.assigned_user_id' => '6a0469ae129e80329',
  'espocrm.prima_nota.default_beneficiary_name' => 'Safe House',
  'espocrm.prima_nota.default_subject_name' => 'Donatore',
);
